### ISSUE TITLE
Set up GPU Environment.

### ISSUE THREAD

**Issue by ftk7810** [JeetDarekar001/FastApi-Bark#1]
Assuming I don't have a GPU environment, How can I set it up? I know how to set it up for other projects, But since it creates a new Environment using venv, How can I make this environment GPU compatible?

**Comment by abhijitdarekar** [comment]
hi @ftk7810 , I ran the notebook [Example Notebook](https://github.com/sunoai/bark/blob/main/notebooks/use_small_models_on_cpu.ipynb), I was able to generate inference.  
However it may take time to generate inference on CPU.

Add below two lines while importing bark. 
`
import os

os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ["SUNO_USE_SMALL_MODELS"] = "1"
`
set CUDA_VISIBLE_DEVICES to empty string while executing this sets code not to use GPU while executing a job.

To set GPU again to run a job :
`os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.

Additionally for you can use smaller versions of BARK  by following.
`import os
os.environ["SUNO_OFFLOAD_CPU"] = "True"
os.environ["SUNO_USE_SMALL_MODELS"] = "True"`

**Comment by ftk7810** [comment]
> hi @ftk7810 , I ran the notebook [Example Notebook](https://github.com/sunoai/bark/blob/main/notebooks/use_small_models_on_cpu.ipynb), I was able to generate inference. However it may take time to generate inference on CPU.
> 
> Add below two lines while importing bark. ` import os
> 
> os.environ["CUDA_VISIBLE_DEVICES"] = "" os.environ["SUNO_USE_SMALL_MODELS"] = "1" ` set CUDA_VISIBLE_DEVICES to empty string while executing this sets code not to use GPU while executing a job.
> 
> To set GPU again to run a job : `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.
> 
> Additionally for you can use smaller versions of BARK by following. `import os os.environ["SUNO_OFFLOAD_CPU"] = "True" os.environ["SUNO_USE_SMALL_MODELS"] = "True"`

Oh wow I never knew I could control that using the enviroment variables, That's really useful, Thank you for your response, Great repo btw I love it.
